-- =======================================================
-- EVOLVR DB SEED DATA
-- =======================================================
-- Note: Replace the UUIDs in the "users" table with ACTUAL UUIDs
-- generated by Supabase Authentication when you sign up test users!
-- The foreign key "id UUID PRIMARY KEY REFERENCES auth.users" requires
-- the user to exist in Supabase Auth first.

-- 1. Districts
INSERT INTO districts (id, name) VALUES 
('11111111-1111-1111-1111-111111111111', 'Lagos Education District 1'),
('22222222-2222-2222-2222-222222222222', 'Lagos Education District 2')
ON CONFLICT (id) DO NOTHING;

-- 2. Schools
INSERT INTO schools (id, district_id, name) VALUES 
('33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'Grace High School'),
('44444444-4444-4444-4444-444444444444', '22222222-2222-2222-2222-222222222222', 'Pioneer Academy')
ON CONFLICT (id) DO NOTHING;

-- 3. Users (IMPORTANT: These IDs must exist in auth.users first. Create 2 users in Supabase Auth and replace the IDs here)
-- Replace 'aaaa...' with a Teacher UUID from Supabase Auth
-- Replace 'bbbb...' with a Student UUID from Supabase Auth
/* 
INSERT INTO users (id, school_id, name, email, role) VALUES 
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '33333333-3333-3333-3333-333333333333', 'Mr. Smith', 'smith@gracehigh.edu', 'teacher'),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '33333333-3333-3333-3333-333333333333', 'John Doe', 'john.doe@student.edu', 'student')
ON CONFLICT (id) DO NOTHING;

-- 4. Teachers
INSERT INTO teachers (id, user_id) VALUES 
('55555555-5555-5555-5555-555555555555', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')
ON CONFLICT (id) DO NOTHING;

-- 5. Students
INSERT INTO students (id, user_id, grade_level, current_path_id, total_minutes) VALUES 
('66666666-6666-6666-6666-666666666666', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 10, 'math_algebra_1', 120)
ON CONFLICT (id) DO NOTHING;

-- 6. Classes
INSERT INTO classes (id, school_id, teacher_id, name) VALUES 
('77777777-7777-7777-7777-777777777777', '33333333-3333-3333-3333-333333333333', '55555555-5555-5555-5555-555555555555', '10th Grade Algebra')
ON CONFLICT (id) DO NOTHING;

-- 7. Class Enrollments
INSERT INTO class_enrollments (id, student_id, class_id) VALUES 
('88888888-8888-8888-8888-888888888888', '66666666-6666-6666-6666-666666666666', '77777777-7777-7777-7777-777777777777')
ON CONFLICT (id) DO NOTHING;
*/

-- 8. Standards (Curriculum Map)
INSERT INTO standards (id, code, description) VALUES 
('99999999-9999-9999-9999-999999999999', 'MATH.ALG.1', 'Core concepts of Algebra including linear equations.'),
('00000000-0000-0000-0000-000000000001', 'MATH.GEO.1', 'Fundamentals of Geometry.')
ON CONFLICT (id) DO NOTHING;

-- 9. Skills (Granular learning nodes)
INSERT INTO skills (id, standard_id, name, description) VALUES 
('00000000-0000-0000-0000-000000000002', '99999999-9999-9999-9999-999999999999', 'Solving Single-Variable Equations', 'Isolating the variable in a basic linear equation.'),
('00000000-0000-0000-0000-000000000003', '99999999-9999-9999-9999-999999999999', 'Systems of Equations', 'Solving two linear equations simultaneously.')
ON CONFLICT (id) DO NOTHING;

-- 10. Lessons
INSERT INTO lessons (id, title, difficulty, description) VALUES 
('00000000-0000-0000-0000-000000000004', 'Intro to Algebra', 'Beginner', 'The basics of solving for x.'),
('00000000-0000-0000-0000-000000000005', 'Advanced Systems', 'Hard', 'Substitution and elimination methods.')
ON CONFLICT (id) DO NOTHING;

-- 11. Lesson Standard Alignments
INSERT INTO lesson_standard_alignments (id, lesson_id, standard_id) VALUES 
('00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000004', '99999999-9999-9999-9999-999999999999')
ON CONFLICT (id) DO NOTHING;

-- 12. Questions
-- Note the content_payload JSONB structure here.
INSERT INTO questions (id, lesson_id, skill_id, difficulty_parameter, discrimination_parameter, content_payload) VALUES 
('00000000-0000-0000-0000-000000000007', '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000002', -1.5, 1.0, 
'{
    "type": "multiple_choice",
    "question": "Solve for x: 2x = 10",
    "options": ["2", "4", "5", "10"],
    "answer": "5",
    "explanation": "Divide both sides by 2."
}'),
('00000000-0000-0000-0000-000000000008', '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000002', 0.5, 1.2, 
'{
    "type": "multiple_choice",
    "question": "Solve for x: 3x + 4 = 19",
    "options": ["3", "5", "7", "15"],
    "answer": "5",
    "explanation": "Subtract 4 from both sides to get 3x = 15, then divide by 3."
}')
ON CONFLICT (id) DO NOTHING;

-- 13. Question Hints
INSERT INTO question_hints (id, question_id, hint_level, content_payload) VALUES 
('00000000-0000-0000-0000-000000000009', '00000000-0000-0000-0000-000000000008', 1, '{"text": "Try to isolate the term with x first. What happens if you subtract 4 from both sides?"}'),
('00000000-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000008', 2, '{"text": "3x = 15. Now divide by 3."}')
ON CONFLICT (id) DO NOTHING;
